on:
  push:
    branches:
      - release
name: release-please
jobs:
  release-please:
    name : releasePlz
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.rp.outputs.releases_created }}
      upload_url: ${{ steps.rp.outputs.upload_url }}
    steps:
      - id: rp
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          default-branch: release
  
  build:
    name : build
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 7.0.x
             
      - name: Restore Dependencies
        run: dotnet restore
          
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
                               
      - name: Build Plugin
        run: |
          invoke-expression 'dotnet build --no-restore --configuration Release TakeMeEverywhere'
           
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: .\TakeMeEverywhere\bin\Release\net7.0-windows\TakeMeEverywhere\

  release:
    name: release
    needs: [release-please, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: artifact/latest.zip
          asset_name: latest.zip
          asset_content_type: application/zip

      - name: Trigger Repo Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/Dalamud_Plugins
          event-type: new-release
